<<<<<<< HEAD
services:
  - type: web
    name: coil-calculator-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          type: web
          property: host
=======
services:
  - type: web
    name: coil-calculator-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          type: web
          property: host
>>>>>>> bfc12cde6c003c10313d7bb9d6a3cc210d063bf4
